In [1]:
import numpy as np
import pandas as pd

In [11]:
movies=pd.read_csv('movies_dataframe.csv')
movies.set_index("imdb_id",inplace=True)
movies

,title_x,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
imdb_id,,,,,,,,,,,,,,,,,
tt8291224,Uri: The Surgical Strike,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
tt9472208,Battalion 609,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
tt6986710,The Accidental Prime Minister (film),https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
tt8108208,Why Cheat India,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
tt6028796,Evening Shadows,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
tt0301250,Tera Mera Saath Rahen,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
tt0298607,Yeh Zindagi Ka Safar,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
tt0069204,Sabse Bada Sukh,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
tt10833860,Daaka,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
tt2403201,Humsafar,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [12]:
#selecting cols from dataframe
#single cols
movies["title_x"]   #this is series

imdb_id
tt8291224                 Uri: The Surgical Strike
tt9472208                            Battalion 609
tt6986710     The Accidental Prime Minister (film)
tt8108208                          Why Cheat India
tt6028796                          Evening Shadows
                              ...
tt0301250                    Tera Mera Saath Rahen
tt0298607                     Yeh Zindagi Ka Safar
tt0069204                          Sabse Bada Sukh
tt10833860                                   Daaka
tt2403201                                 Humsafar
Name: title_x, Length: 1629, dtype: str

In [13]:
#multiple cols
movies[["title_x","actors","year_of_release"]]   #dataframe

,title_x,actors,year_of_release
imdb_id,,,
tt8291224,Uri: The Surgical Strike,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,2019
tt9472208,Battalion 609,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,2019
tt6986710,The Accidental Prime Minister (film),Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,2019
tt8108208,Why Cheat India,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,2019
tt6028796,Evening Shadows,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,2018
...,...,...,...
tt0301250,Tera Mera Saath Rahen,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,2001
tt0298607,Yeh Zindagi Ka Safar,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,2001
tt0069204,Sabse Bada Sukh,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,2018
tt10833860,Daaka,Gippy Grewal|Zareen Khan|,2019
tt2403201,Humsafar,Fawad Khan|,2011

In [14]:
# Create a Pandas DataFrame
df = pd.DataFrame([['a','b'], ['c','d'], ['e','f'], ['g','h']], columns=['col1', 'col2'])

# Display the DataFrame
print("Input DataFrame:")
print(df)

# Slice rows based on position
result = df.iloc[1:3, :]
print("Output:")
print(result)

Input DataFrame:
  col1 col2
0    a    b
1    c    d
2    e    f
3    g    h
Output:
  col1 col2
1    c    d
2    e    f

In [15]:
movies.iloc[:5,0:4]   #dataframe

,title_x,poster_path,wiki_link,title_y
imdb_id,,,,
tt8291224,Uri: The Surgical Strike,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike
tt9472208,Battalion 609,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609
tt6986710,The Accidental Prime Minister (film),https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister
tt8108208,Why Cheat India,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India
tt6028796,Evening Shadows,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows

In [16]:
#Slicing DataFrame Rows and Columns using .loc[]
df = pd.DataFrame([['a','b'], ['c','d'], ['e','f'], ['g','h']], columns=['col1', 'col2'], index=['r1', 'r2', 'r3', 'r4'])

# Display the DataFrame
print("Original DataFrame:")
print(df)

# Slice rows and columns by label
result = df.loc['r1':'r3', 'col1']
print("Output:")
print(result)

Original DataFrame:
   col1 col2
r1    a    b
r2    c    d
r3    e    f
r4    g    h
Output:
r1    a
r2    c
r3    e
Name: col1, dtype: str

In [19]:
movies.loc['tt8291224':'tt8108208',:'wiki_link']   #dataframe

,title_x,poster_path,wiki_link
imdb_id,,,
tt8291224,Uri: The Surgical Strike,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...
tt9472208,Battalion 609,NaN,https://en.wikipedia.org/wiki/Battalion_609
tt6986710,The Accidental Prime Minister (film),https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...
tt8108208,Why Cheat India,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India

In [20]:
movies.loc[:,:'title_x']   #dataframe

                                         title_x
imdb_id
tt8291224               Uri: The Surgical Strike
tt9472208                          Battalion 609
tt6986710   The Accidental Prime Minister (film)
tt8108208                        Why Cheat India
tt6028796                        Evening Shadows
...                                          ...
tt0301250                  Tera Mera Saath Rahen
tt0298607                   Yeh Zindagi Ka Safar
tt0069204                        Sabse Bada Sukh
tt10833860                                 Daaka
tt2403201                               Humsafar

[1629 rows x 1 columns]

In [21]:
#Modifying Values After Slicing

# Create a DataFrame
df = pd.DataFrame([['a', 'b'], ['c', 'd'], ['e', 'f'], ['g', 'h']], 
                  columns=['col1', 'col2'])

# Display the Original DataFrame
print("Original DataFrame:", df, sep='\n')

# Modify a subset of the DataFrame using iloc
df.iloc[1:3, 0] = ['x', 'y']

# Display the modified DataFrame
print('Modified DataFrame:',df, sep='\n')

Original DataFrame:
  col1 col2
0    a    b
1    c    d
2    e    f
3    g    h
Modified DataFrame:
  col1 col2
0    a    b
1    x    d
2    y    f
3    g    h